function handleException (errMessage: string) : never{
    throw Error(errMessage);
}